Review-zip/ReviewZip-BE

src/main/java/com/example/ReviewZIP/domain/user/UsersController.java

[CI] github action

---

.github/workflows/dev-deploy.yml

[ci] github actions

---

.github/workflows/dev-deploy.yml

[ci] github action 코드 수정

---

.github/workflows/dev-deploy.yml

[ci] github actions 코드 수정

---

.github/workflows/dev-deploy.yml

[ci ]: github action 수정

---

.github/workflows/dev-deploy.yml

[ci] github actions 수정

---

.github/workflows/dev-deploy.yml

[ci] github action 코드 추가

---

.github/workflows/dev-deploy.yml
.gitmodules
build.gradle
src/main/java/com/example/ReviewZIP/ReviewZipApplication.java

[ci] gitaction submodule 추가

---

.github/workflows/dev-deploy.yml

- 서버에서 자동 배포되는 코드 작성
```
code-deploy:
needs: build-and-push-image
runs-on: ubuntu-latest
steps:
- name: Checkout repository
uses: actions/checkout@v2
- name: Access to server and Run container
uses: appleboy/ssh-action@master
with:
host: ${{ secrets.SERVER_IP }}
username: ${{ secrets.SERVER_USER }}
password: ${{ secrets.SSH_PASSWORD }}
script: |
cd reviewzip-server
docker-compose down
docker-compose rm
docker rmi ${{ secrets.IMAGE_NAME }}
docker pull ${{ secrets.IMAGE_NAME }}
docker-compose up -d
```
- 해당 환경변수는 저희 repository 환경변수에 저장되어 있습니다.

[CI ] 자동배포 파일 생성

---

src/main/java/com/example/ReviewZIP/domain/post/PostsController.java
src/main/java/com/example/ReviewZIP/domain/post/PostsConverter.java
src/main/java/com/example/ReviewZIP/domain/post/PostsRepository.java
src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
src/main/java/com/example/ReviewZIP/domain/post/dto/request/PostRequestDto.java
src/main/java/com/example/ReviewZIP/domain/post/dto/response/PostResponseDto.java
src/main/java/com/example/ReviewZIP/domain/postLike/PostLikesRepository.java
src/main/java/com/example/ReviewZIP/domain/scrab/ScrabsRepository.java
src/main/java/com/example/ReviewZIP/global/response/code/resultCode/ErrorStatus.java

로그의 특정 유저의 게시물 가져오기를 참고하여 작성하였습니다.
코드가 유사한 부분이 몇몇 존재합니다.
```
@Query("SELECT count(p) FROM Posts p WHERE p.user != :user")
long countByUserNot(@Param("user") Users user);
Page<Posts> findAllByUserNot(Users user, PageRequest pageRequest);
```
- 쿼리문을 사용하여 사용자가 아닌 유저가 쓴 post의 개수를 세도록 함
- PageRequest 페이징 처리를 위한 객체
- Posts 테이블에서 user가 아닌 다른 사람이 작성한 게시물을 페이지 단위로 모두 찾도록 함
```
@Transactional
public List<PostResponseDto.PostInfoDto> getRandomPostInfoDto(Long userId) {
Users user = usersRepository.getById(userId);
long qty = postsRepository.countByUserNot(user);
if (qty < 3) {
throw new PostsHandler(ErrorStatus.POST_RANDOM_FAIL);
}
Set<Integer> randomIndices = new HashSet<>();
while (randomIndices.size() < 3) {
int idx = (int)(Math.random() * qty);
randomIndices.add(idx);
} …
```

[Feat] 랜덤으로 게시글 3개 가져오기

---

src/main/java/com/example/ReviewZIP/domain/image/ImagesController.java
src/main/java/com/example/ReviewZIP/domain/post/PostsController.java
src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsController.java
src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
src/main/java/com/example/ReviewZIP/domain/user/dto/response/UserResponseDto.java
src/main/java/com/example/ReviewZIP/global/response/code/resultCode/ErrorStatus.java

[Docs] swagger 응답 작성

---

src/main/java/com/example/ReviewZIP/domain/post/PostsController.java
src/main/java/com/example/ReviewZIP/domain/post/PostsConverter.java
src/main/java/com/example/ReviewZIP/domain/post/PostsRepository.java
src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
src/main/java/com/example/ReviewZIP/domain/user/dto/request/FollowRequestDto.java

---
</br>
---
- 팔로워/ 팔로잉 목록이 없을 때
- 게시글 또는 스크랩한 글의 목록이 없을 때
</br>
- import 중복 혹은 사용하지 않을 때 삭제 후 merge하는 것을 권고드립니다.

[Refactor] 불필요한 예외처리 삭제

---

build.gradle
src/main/java/com/example/ReviewZIP/domain/jwt/JwtProperties.java
src/main/java/com/example/ReviewZIP/domain/jwt/TokenProvider.java
src/main/java/com/example/ReviewZIP/domain/oauth/KakaoController.java
src/main/java/com/example/ReviewZIP/domain/oauth/OauthService.java
src/main/java/com/example/ReviewZIP/domain/oauth/dto/Response/OauthResponseDto.java
src/main/java/com/example/ReviewZIP/domain/oauth/dto/request/OauthRequestDto.java
src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
src/main/java/com/example/ReviewZIP/domain/user/Users.java
src/main/java/com/example/ReviewZIP/domain/user/UsersRepository.java

[Feat] 카카오 로그인 구현

---

src/main/java/com/example/ReviewZIP/domain/oauth/KakaoController.java
src/main/java/com/example/ReviewZIP/domain/oauth/OauthService.java
src/main/java/com/example/ReviewZIP/domain/oauth/dto/request/OauthRequestDto.java
src/main/java/com/example/ReviewZIP/global/response/code/resultCode/ErrorStatus.java
src/main/java/com/example/ReviewZIP/global/response/exception/handler/GeneralHandler.java

[docs] 카카오 로그인  swagger 추가

---

src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
src/main/java/com/example/ReviewZIP/domain/user/UsersService.java

---
- 아직 본인인증 구현이 이루어지지 않았으므로 user id가 1인 유저를 나로 설정하였습니다.
```java
@GetMapping("/me/following")
@Operation(summary = "나의 팔로잉 목록 가져오기 API",description = "토큰 인증 후 나의 팔로잉 목록 조회, FollowingPreviewDto와 FollowingPreviewListDto 이용, 임시로 user id 1의 팔로잉 목록 반환")
@io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "USER404", description = "토큰에 해당하는 유저 없음",content = @Content(schema = @Schema(implementation = ApiResponse.class))),
})
@Parameters({
@Parameter(name = "page", description = "페이지 번호"),
@Parameter(name = "size", description = "페이징 사이즈")
})
public ApiResponse<FollowResponseDto.FollowingPreviewListDto> getUserFollowingList(@RequestParam(name = "page") Integer …
```

[Feat] 나의 팔로잉 목록 조회 API

---

src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
src/main/java/com/example/ReviewZIP/domain/user/UsersService.java

---
- 토큰 인증 구현 전이므로 user id 1인 유저를 나로 설정했습니다.
```java
@GetMapping("/me/followers")
@Operation(summary = "나의 팔로워 목록 가져오기 API",description = "토큰 인증 후 나의 팔로워 목록 조회, FollowerPreviewDto와 FollowerPreviewListDto 이용")
@io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "USER404", description = "토큰에 해당하는 유저 없음",content = @Content(schema = @Schema(implementation = ApiResponse.class))),
})
@Parameters({
@Parameter(name = "page", description = "페이지 번호"),
@Parameter(name = "size", description = "페이징 사이즈")
})
public ApiResponse<FollowResponseDto.FollowerPreviewListDto> getUserFollowerList(@RequestParam(name = "page") Integer page, @RequestParam(name = "size") Integer …
```

[Feat] 나의 팔로워 목록 가져오기

---

src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
src/main/java/com/example/ReviewZIP/domain/user/UsersService.java

---
- 토큰 인증 구현 전으로 user id 1을 나로 설정
```java
@GetMapping("/me/posts/scrabs")
@Operation(summary = "내가 스크랩한 게시물 가져오기 API",description = "토큰 인증 후 스크랩한 게시글들의 목록(대표 이미지들)을 반환, PostPreviewDto와 PostPreviewListDto 이용")
@io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "USER404", description = "토큰에 해당하는 유저 없음",content = @Content(schema = @Schema(implementation = ApiResponse.class))),
})
@Parameters({
@Parameter(name = "page", description = "페이지 번호"),
@Parameter(name = "size", description = "페이징 사이즈")
})
public ApiResponse<UserResponseDto.PostPreviewListDto> getUserScrabList(@RequestParam(name = "page")Integer page, @RequestParam(name = "size") Integer size) { …
```

[Feat] 내가 스크랩한 게시글 목록 가져오기

---

src/main/java/com/example/ReviewZIP/global/s3/S3Service.java

fix: imageUrl 수정

---

src/main/java/com/example/ReviewZIP/domain/post/PostsConverter.java
src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
src/main/java/com/example/ReviewZIP/domain/post/dto/response/PostResponseDto.java

---
- 프론트의 서버가 리눅스를 이용하여 UTC(세계 협정시)를 사용하므로 시간 계산시 현재 시간을 UTC로 변경이 필요했다.
</br>
```java
public String getCreatedAt(LocalDateTime createdAt){
// 서버시간을 UTC로 설정
ZoneId serverZone = ZoneId.of("UTC");
LocalDateTime now = ZonedDateTime.now(serverZone).toLocalDateTime();
Duration duration = Duration.between(createdAt, now);
long minutes = duration.toMinutes();
long hours = duration.toHours();
if (minutes < 60){
return minutes + "분 전";
} else if (hours < 24){
return hours + "시간 전";
} else{
DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy년 MM월 dd일");
return createdAt.format(formatter);
}
}
```
Duration에서 제공하는 .between(과거LocalDateTime, 현재LocalDateTime)을 이용하여 시간의 차를 계산한 후 해당 시간에 맞는 포맷을 반환하도록 하였습니다.
</br>
- PostInfoDto에서 createdAt은 LocalDateTime에서 String으로 변경하였습니다.
- 이에 Converter를 변경하여 …

[Refactor] 생성 시간 포맷 수정

---

src/main/java/com/example/ReviewZIP/domain/follow/FollowsController.java
src/main/java/com/example/ReviewZIP/domain/post/PostsController.java
src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
src/main/java/com/example/ReviewZIP/domain/post/dto/response/PostResponseDto.java
src/main/java/com/example/ReviewZIP/domain/scrab/Scrabs.java
src/main/java/com/example/ReviewZIP/domain/scrab/ScrabsRepository.java
src/main/java/com/example/ReviewZIP/domain/user/UsersController.java

---
- @PathVariable로 postId를 받아 해당 post를 스크랩하여 Scrabs 객체를 생성하고 삭제하는 api 구현했습니다.
</br>
```java
@Transactional
public void createScrabs(Long postId){
// userId는 1로 대체
Users me = usersRepository.getById(1L);
Posts post = postsRepository.findById(postId).orElseThrow(()->new PostsHandler(ErrorStatus.POST_NOT_FOUND));
Scrabs newScrab = Scrabs.builder()
.user(me)
.post(post)
.build();
scrabsRepository.save(newScrab);
}
@Transactional
public void deleteScrabs(Long postId){
// userId는 1로 대체
Users me = usersRepository.getById(1L);
Posts post = postsRepository.findById(postId).orElseThrow(()->new PostsHandler(ErrorStatus.POST_NOT_FOUND));
Scrabs scrabs = scrabsRepository.findByUserAndPost(me, post);
scrabsRepository.delete(scrabs);
}
```
- 유저는 1L로 설정하여 진행하였습니다.

[Feat] 게시글 스크랩하기/취소하기

---

src/main/java/com/example/ReviewZIP/domain/follow/FollowsRepository.java
src/main/java/com/example/ReviewZIP/domain/post/PostsController.java
src/main/java/com/example/ReviewZIP/domain/post/PostsConverter.java
src/main/java/com/example/ReviewZIP/domain/post/PostsRepository.java
src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
src/main/java/com/example/ReviewZIP/domain/post/dto/response/PostResponseDto.java
src/main/java/com/example/ReviewZIP/domain/user/UsersController.java

---
```java
public List<Long> getFollowigIdList(){
// 일단 1L로 나를 대체
Users me = usersRepository.getById(1L);
List<Follows> followingList = followsRepository.findAllBySender(me);
List<Long> followingIdList = new ArrayList<>();
for (Follows following : followingList){
Long followingId = following.getReceiver().getId();
followingIdList.add(followingId);
}
return followingIdList;
}
```
- 내가 팔로우하는 대상의 id를 가져와야하는데 해당 follows 객체의 아이디를 가져와 잘못된 값을 반환하고 있었습니다. 수정하여 제대로 작동하는 것 확인했습니다.
</br>
```java
@GetMapping("/me/followers")
@Operation(summary = "나의 팔로워 목록 가져오기 API",description = "토큰 인증 후 나의 팔로잉 목록 조회, FollowerPreviewDto와 FollowerPreviewListDto 이용, 임시로 user id 1의 팔로잉 목록 반환") …
```

[Fix] 함수 오류 수정 & 필요한 함수 반환값 추가

---

src/main/java/com/example/ReviewZIP/domain/user/UsersService.java

```java
Optional<SearchHistories> existingRecord = searchHistoriesRepository.findByContentAndUser(name, users);
if (existingRecord.isEmpty()) {
SearchHistories searchHistories = SearchHistories.builder()
.content(name)
.type(SearchType.NAME)
.user(users)
.build();
searchHistoriesRepository.save(searchHistories);
}
```
해당 검색 기록 저장 부분을 삭제하여 유저 검색의 기능만 남겼습니다.

[Refactor] 유저 검색기록 저장 부분 삭제

---

src/main/java/com/example/ReviewZIP/domain/follow/FollowsRepository.java
src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsController.java
src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsConverter.java
src/main/java/com/example/ReviewZIP/domain/postHashtag/dto/response/PostHashtagResponseDto.java
src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
src/main/java/com/example/ReviewZIP/domain/user/UsersConverter.java
src/main/java/com/example/ReviewZIP/domain/user/UsersRepository.java
src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
src/main/java/com/example/ReviewZIP/domain/user/dto/response/FollowResponseDto.java
src/main/java/com/example/ReviewZIP/domain/user/dto/response/UserResponseDto.java

---
- 반환값이 Page인 함수들은 List로 반환되도록 수정하였습니다. swagger로 수정한 API의 결과 확인 완료 했습니다.
- 수정한 함수목록은 다음과 같습니다.
- 자세한 사항은 Files changed에서 확인해 주세요. 주로 ListDto 삭제 및 Page -> List 수정입니다.
</BR>
- 나의 팔로잉, 나의 팔로워, 특정유저의 팔로잉, 특정유저의 팔로워 목록 가져오기
- 유저 이름, 유저 닉네임, 해시태그 검색하기
</BR>
---
- 유저 이름 및 닉네임 검색에 Query문이 동작하도록 하였습니다.

[Feat] 일부 함수 반환값 수정

---

src/main/java/com/example/ReviewZIP/domain/searchHistory/SearchHistories.java
src/main/java/com/example/ReviewZIP/domain/searchHistory/SearchHistoriesController.java
src/main/java/com/example/ReviewZIP/domain/searchHistory/SearchHistoriesRepository.java
src/main/java/com/example/ReviewZIP/domain/searchHistory/SearchHistoriesService.java
src/main/java/com/example/ReviewZIP/domain/user/Users.java
src/main/java/com/example/ReviewZIP/global/response/code/resultCode/ErrorStatus.java
src/main/java/com/example/ReviewZIP/global/response/exception/handler/HistoryHandler.java

---
```java
public enum SearchType {
USER,
HASHTAG
}
```
- 해당 타입은 추후 검색기록 목록 가져오기에 이용될 예정입니다.
</ br>
```java
@Transactional
public void saveUserSearchHistory(Long userId, Long objectId){
Users me = usersRepository.getById(1L);
Users object = usersRepository.findById(objectId).orElseThrow(()->new UsersHandler(ErrorStatus.USER_NOT_FOUND));
SearchHistories userHistory = SearchHistories.builder()
.type(SearchType.USER)
.user(me)
.object(object)
.hashtag(null)
.build();
searchHistoriesRepository.save(userHistory);
}
@Transactional
public void deleteUserSearchHistory(Long userId, Long objectId){
Users me = usersRepository.getById(userId);
Users object = usersRepository.findById(objectId).orElseThrow(()->new UsersHandler(ErrorStatus.USER_NOT_FOUND));
SearchHistories history = …
```

[Feat] 유저 및 해시태그 검색 기록 저장 및 삭제

---

src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
src/main/java/com/example/ReviewZIP/domain/user/UsersConverter.java
src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
src/main/java/com/example/ReviewZIP/domain/user/dto/response/UserResponseDto.java

---
- UserPreviewDto 통일성을 위한 코드 수정입니다.
```java
public static class UserPreviewDto {
private Long userId;
private String nickname;
private String name;
private String profileUrl;
private boolean following;
}
```
</br>
- 리뷰 확인 후 수정하는 것을 잊었습니다. 검색 목록 가져오기에서 최신순으로 List를 반환하도록 수정하였습니다.
```java
public List<SearchHistories> getHistoryList(Long userId){
Users me = usersRepository.getById(userId);
List<SearchHistories> historyList =  me.getSearchHistoriesList();
Collections.reverse(historyList);
return historyList;
}
```

[Refactor] dto 및 검색기록 최신순 정렬

---

src/main/java/com/example/ReviewZIP/domain/post/PostsController.java
src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
src/main/java/com/example/ReviewZIP/global/response/code/resultCode/ErrorStatus.java

- 매직넘버 대신 상수를 선언하여 사용
- 랜덤으로 3개의 게시물 가져오기 url 변경 `v1/posts/random-three`
- 랜덤으로 하나의 게시물 가져오기 `v1/posts/random-one`
```java
@GetMapping("/random-one")
@Operation(summary = "랜덤으로 게시글 1개 가져오기 API", description = "PostInfoDto")
@io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "POST405", description = "랜덤으로 1개의 게시글 가져오기 실패",content = @Content(schema = @Schema(implementation = ApiResponse.class))),
})
public ApiResponse<PostResponseDto.PostInfoDto> getRandomPost(@RequestParam Long userId) {
PostResponseDto.PostInfoDto randomPostInfoDto = postsService.getOneRandomPostInfoDto(userId);
return ApiResponse.onSuccess(randomPostInfoDto);
}
```
```java
public …
```

[Feat] 랜덤으로 하나의 게시물 가져오기

---

src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
src/main/java/com/example/ReviewZIP/domain/searchHistory/SearchHistoriesController.java
src/main/java/com/example/ReviewZIP/global/logback/LoggingFilter.java
src/main/resources/logback.xml

- 프론트의 요구에 따라 Hibernate SQL 쿼리 로깅 안되게 수정
- [Request] [GET] /v1/posts/random-one URL 형식으로 출력
- .yml 파일 수정하였으므로 
서브모듈 업데이트 부탁드립니다.
```java
[2024-02-06 17:55:57.867] [http-nio-8080-exec-1] [traceId=42500848-cfab-42a2-a96d-1de3c6368c12] INFO  LoggingFilter - [Request] [GET] /v1/posts/random-one
[2024-02-06 17:55:58.189] [http-nio-8080-exec-1] [traceId=42500848-cfab-42a2-a96d-1de3c6368c12] INFO  LoggingFilter - [Response]
```

[Refactor] logging modify

---

src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
src/main/java/com/example/ReviewZIP/domain/user/UsersConverter.java
src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
src/main/java/com/example/ReviewZIP/domain/user/dto/response/FollowResponseDto.java
src/main/java/com/example/ReviewZIP/domain/user/dto/response/UserResponseDto.java

- 팔로잉 / 팔로워 목록 가져오기에서 following 여부 추가
- 나의 정보 가져오기 API 추가
- followingId 및 followerId -> userId 변경
```java
@GetMapping("/me")
@Operation(summary = "나의 정보(프로필) API 가져오기",description = " 나의 정보를 가져오기, UserInfoDto 이용")
})
public ApiResponse<UserResponseDto.UserInfoDto> getUserInfo(){
return ApiResponse.onSuccess(usersService.getUserInfo(1L));
}
```

[Feat] 내 정보 가져오기 API

---

src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsController.java
src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsConverter.java
src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsRepository.java

---
- 해시태그 검색시 결과값이 중복으로 나오는 부분 수정

[Refactor] 해시태그로 해시태그 검색 수정

---

src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
src/main/java/com/example/ReviewZIP/domain/post/dto/request/PostRequestDto.java

- 이미지 dto 변경으로 게시글 생성시 이미지가 삽입되지않아 오류 수정

[Fix] main merge

---

src/main/java/com/example/ReviewZIP/domain/post/PostsConverter.java
src/main/java/com/example/ReviewZIP/domain/post/dto/response/PostResponseDto.java

- 게시글들 정보 가져올 때 스크랩한 수 가져오기 추가

[Dev] main merge

---

src/main/java/com/example/ReviewZIP/domain/token/RefreshTokenService.java
src/main/java/com/example/ReviewZIP/domain/user/UsersConverter.java
src/main/java/com/example/ReviewZIP/domain/user/dto/response/UserResponseDto.java

---
- 해시태그값만 반환하였었는데 hashtagId, tagName, postNum(해당 해시태그를 갖는 게시글의 갯수) 반환값 수정하였으며 해시태그id는 가장 최신것을 갖도록 하였습니다.
```java
public static UserResponseDto.PostHashtagsPreviewDto toHashtagPreviewDto(String hashtag){
List<PostHashtags> postHashtagsRepositoryList = postHashtagsRepository.findAllByHashtag(hashtag);
int lastIndex = postHashtagsRepositoryList.size() - 1;
PostHashtags latestHashtag = postHashtagsRepositoryList.get(lastIndex);
return UserResponseDto.PostHashtagsPreviewDto.builder()
.hashtagId(latestHashtag.getId())
.tagName(hashtag)
.postNum(postHashtagsRepositoryList.size())
.build();
}
```
</br>
---
```json
{
"isSuccess": true,
"code": "COMMON200",
"message": "성공입니다.",
"result": [
{
"historyId": 39,
"type": "HASHTAG",
"user": null,
"hashtag": {
"hashtagId": 49,
"tagName": "인하대", …
```

[Refactor] 검색기록 가져오기 API 수정

---

src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
src/main/java/com/example/ReviewZIP/global/security/UserDetailsServiceImpl.java

---
- UserDetails를 받아 해당 유저를 UserDetailsImpl 객체로 변환 후 user의 id를 반환하는 함수입니다.
```java
public Long getUserId(UserDetails user){
String username = user.getUsername();
UserDetailsImpl userDetails = userDetailsService.loadUserByUsername(username);
return userDetails.getUserId();
}
```
</br>
- 원래 유저의 email을 받아 UserDetails를 반환하는 함수이지만 UserDetailsImple의 생성자이므로 UserDetailsImple를 반환하도록 수정하였습니다.
```java
public UserDetailsImpl loadUserByUsername(String email) throws UsernameNotFoundException {
Users user = usersRepository.findByEmail(email).orElseThrow(() -> new UsernameNotFoundException("User not found"));
return new UserDetailsImpl(user);
}
```
</br>
- 가독성을 위하여 swagger는 제거하였습니다.
- 해당 어노테이션을 통해서 UserDetails 객체인 user가 생성됩니다.
- 1L로 대체되었던 userId가 들어가는 부분에 아래의 함수대로 적어주시면 됩니다.
```java …
```

[Feat] 토큰 이용 아이디 반환

---

src/main/java/com/example/ReviewZIP/domain/follow/FollowsController.java
src/main/java/com/example/ReviewZIP/domain/follow/FollowsService.java
src/main/java/com/example/ReviewZIP/domain/post/PostsController.java
src/main/java/com/example/ReviewZIP/domain/post/PostsRepository.java
src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
src/main/java/com/example/ReviewZIP/domain/searchHistory/SearchHistoriesController.java
src/main/java/com/example/ReviewZIP/domain/searchHistory/SearchHistoriesRepository.java
src/main/java/com/example/ReviewZIP/domain/searchHistory/SearchHistoriesService.java
src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
src/main/java/com/example/ReviewZIP/domain/user/UsersService.java

---
- 토큰의 이용이 가능해짐에 따라 함수를 수정하였습니다.
</br></br>
</br>
-  특정유저가 스크랩한 게시물 가져오기 함수를 예시로 보여드리겠습니다. 해당 게시물들 중 `내`가 좋아요한 것, `내`가 스크랩한 것, `내` 것인지에 대한 판단이 필요하므로 나에 대한 정보도 가져와야하며, 특정유저의 id 모두 가져와야하므로 두개의 변수를 받도록 작성해줍니다.
- 이 과정을 거치며 꼭 service의 함수가 1L을 받지 않는 지, 결과값이 모두 잘 반환되는지에 대한 확인이 필요합니다. 모든 commit을 적어드리지 못하므로 필요한 부분은 코드 확인해주시면 감사하겠습니다.
- 만약 유저의 아이디를 DTO 값으로 받는 로직이 있다면 해당 request dto는 수정해주세요.
- 참고로 저는 userId라는 변수명을 주로 사용하지만 만약 특정유저와 변수명이 겹치면 myId로 변수명을 설정하여 진행하였습니다.
</br>
```java
@GetMapping("/{userId}/posts")
@Operation(summary = "특정 유저의 게시글 목록 가져오기 API",description = "특정 유저의 id를 받아 게시글들의 목록(대표 이미지들)을 반환, UserInfoDto & ImageDto & HashtagDto & PostInfoDto 이용") …
```

[Refactor] 토큰 인증기반 기능 수정

---

src/main/java/com/example/ReviewZIP/domain/post/Posts.java
src/main/java/com/example/ReviewZIP/domain/post/PostsController.java
src/main/java/com/example/ReviewZIP/domain/post/PostsConverter.java
src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
src/main/java/com/example/ReviewZIP/domain/post/dto/request/PostRequestDto.java
src/main/java/com/example/ReviewZIP/domain/post/dto/response/PostResponseDto.java
src/main/java/com/example/ReviewZIP/domain/store/Stores.java
src/main/java/com/example/ReviewZIP/domain/store/StoresRepository.java
src/main/java/com/example/ReviewZIP/domain/store/dto/request/StoreRequestDto.java

- 지도 정보를 받아와 store 테이블에 저장하고 게시글을 생성
- 토큰 인증 관련 수정
```java
@PostMapping
@Operation(summary = "게시글 생성 API", description = "지도 위치 정보를 store table에 저장하고 게시글을 생성한다. CreatedPostRequestDto, storeInfoDto 사용")
@io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "POST403", description = "게시글 작성 실패",content = @Content(schema = @Schema(implementation = ApiResponse.class))),
})
public ApiResponse<PostResponseDto.PostInfoDto> createPost(@AuthenticationPrincipal UserDetails user, @RequestBody PostRequestDto.CreatedPostRequestDto request){
PostResponseDto.PostInfoDto post = postsService.createPost(usersService.getUserId(user), request);
return …
```

[Refactor] 게시글 생성 리팩터링

---

src/main/java/com/example/ReviewZIP/domain/userStores/UserStores.java
src/main/java/com/example/ReviewZIP/domain/userStores/UserStoresController.java
src/main/java/com/example/ReviewZIP/domain/userStores/UserStoresConverter.java
src/main/java/com/example/ReviewZIP/domain/userStores/UserStoresService.java
src/main/java/com/example/ReviewZIP/domain/userStores/dto/request/UserStoresRequestDto.java
src/main/java/com/example/ReviewZIP/domain/userStores/dto/response/UserStoresResponseDto.java

- stores의 Request Body와 동일하게 수정
- `/v1/user-stores/`에서 url `/v1/user-stores` 수정
```json
{
"name": "string",
"addressName": "string",
"roadAddressName": "string",
"latitude": "string",
"longitude": "string"
}
```
```java
public static UserStores toEntity(UserStoresRequestDto.CreateUserStoresDto request) {
return UserStores.builder()
.name(request.getName())
.road_address_name(request.getRoadAddressName())
.address_name(request.getAddressName())
.latitude(request.getLatitude())
.longitude(request.getLongitude())
.build();
}
```
``` java
public static UserStoresResponseDto.StoreInfoDto toStoreInfoDto(UserStores userStores) {
return UserStoresResponseDto.StoreInfoDto.builder()
.storeId(userStores.getId())
.latitude(userStores.getLatitude())
.longitude(userStores.getLongitude()) …
```

[Refactor] 특정 장소를 관심 장소로 등록 API 수정

---

src/main/java/com/example/ReviewZIP/domain/token/RefreshTokenService.java
src/main/java/com/example/ReviewZIP/domain/user/Users.java
src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
src/main/java/com/example/ReviewZIP/domain/user/UsersConverter.java
src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
src/main/java/com/example/ReviewZIP/domain/user/dto/request/UserRequestDto.java

- 프로필 이미지와 닉네임을 수정하는 API의 코드를 수정했습니다.
- toSignUpDto를 UsersConverter 클래스 안에 선언해 이와 관련된 코드를 리팩토링했습니다.
```java
@Transactional
public UserRequestDto.UserProfileUrlDto updateProfileUrl(Long userId, UserRequestDto.UserProfileUrlDto userProfileUrlDto){
Users user = usersRepository.findById(userId).orElseThrow(() -> new UsersHandler(ErrorStatus.USER_NOT_FOUND));
Images image = imagesRepository.findById(userProfileUrlDto.getImageId()).orElseThrow(() -> new ImagesHandler(ErrorStatus.IMAGE_NOT_PROVIDED));
user.setProfileUrl(image.getUrl());
usersRepository.save(user);
return userProfileUrlDto;
}
```
- image 객체를 통해 해당 imageId를 받습니다. 그리고 user.setProfileUrl(image.getUrl()); 을 선언해 해당 유저의 profileUrl을 수정합니다. 그리고 수정된 정보를 레포지토리에 저장합니다.
```java
@Transactional
public UserRequestDto.UserNicknameDto …
```

[Fix] 프로필 이미지, 닉네임 수정 API 수정 

---

src/main/java/com/example/ReviewZIP/domain/token/RefreshTokenController.java
src/main/java/com/example/ReviewZIP/domain/token/RefreshTokenService.java
src/main/java/com/example/ReviewZIP/domain/user/UsersRepository.java

---
- 닉네임 중복 시 에러가 발생하도록 수정
```java
@Transactional
public SignUpResponseDto signUp(SignUpRequestDto signUpRequestDto) {
if(usersRepository.existsByEmail(signUpRequestDto.getEmail())) {
throw new UsersHandler(ErrorStatus.USER_EXISTS_EMAIL);
}
if(usersRepository.existsByNickname(signUpRequestDto.getNickname())){
throw new UsersHandler(ErrorStatus.USER_EXISTS_NICKNAME);
}
signUpRequestDto.setPassword(encodePassword(signUpRequestDto.getPassword()));
return SignUpResponseDto.signUpResponseDto(usersRepository.save(UsersConverter.toSignUpDto(signUpRequestDto)));
}
```

[Refactor] 회원가입 API

---

src/main/java/com/example/ReviewZIP/domain/image/ImageConverter.java
src/main/java/com/example/ReviewZIP/domain/image/ImagesController.java
src/main/java/com/example/ReviewZIP/domain/image/dto/response/ImageResponseDto.java
src/main/java/com/example/ReviewZIP/domain/post/PostsConverter.java
src/main/java/com/example/ReviewZIP/domain/post/dto/response/PostResponseDto.java
src/main/java/com/example/ReviewZIP/domain/postHashtag/dto/response/PostHashtagResponseDto.java
src/main/java/com/example/ReviewZIP/domain/store/Stores.java

- 해당 객체에 대한 dto를 가져오도록 수정
```java
public class ImageResponseDto {
@Builder
@Getter
@NoArgsConstructor
@AllArgsConstructor
public static class ImageListDto {
private List<Long> imageIds;
}
@Builder
@Getter
@AllArgsConstructor
public static class ImageDto {
private Long imageId;
private String imageUrl;
}
}
```
```java
public class PostResponseDto {
@Builder
@Getter
@NoArgsConstructor
@AllArgsConstructor
public static class UserInfoDto{
private Long userId;
private String name;
private String nickname;
private String profileUrl;
}
@Builder
@Getter
@NoArgsConstructor
@AllArgsConstructor
public static class PostInfoDto{
private Long postId;
private String comment;
private Double point;
private Integer likeNum;
private Integer scrabNum;
private Integer hashtagNum;
private boolean checkLike; …
```

[Refactor] domain dto 리팩터링
